version: '3'

services:
  data_present:
    restart: always
    image: "postgres:13.4-alpine"
    restart: always
    volumes:
        - ./present_data/:/var/lib/postgresql/data/
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: ${PRODUCTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRODUCTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRODUCTS_POSTGRES_DB}
    ports:
        - "5431:5432"


      
  data_courier:
    restart: always
    image: "postgres:13.4-alpine"
    restart: always
    volumes:
        - ./data_courier/:/var/lib/postgresql/data/
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: ${COURIER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${COURIER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${COURIER_POSTGRES_DB}
    ports:
        - "5434:5432"



  present_api:
    restart: always
    build: ./api/presents_service
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - 8001:8000
    depends_on: 
      - data_present
    volumes:
      - ./api/presents_service:/app/presents

  courier_api:
    restart: always
    build: ./api/courier
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - 8002:8000

    depends_on: 
      - data_courier
    volumes:
      - ./api/courier:/app/courier

  front:
    restart: always
    build: ./frontend
    ports:
      - 3001:3000
    # volumes:
    #     - ./frontend/:/app

  # admin:
  #   restart: always
  #   build: ./admin
  #   ports:
  #     - 3002:3000

      

  
   



  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=mba.kimep@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=Ch123456##
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - data_present
  #     - courier_api

  nginx:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    depends_on:
      - present_api
      - courier_api
      - front
      # - admin
    ports:
      - "8080:8080"
      - "3000:3000"
      - "80:80"
      - "443:443"
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"