"""New Migration

Revision ID: 110d5adc1a02
Revises: 314c38d19e23
Create Date: 2021-09-29 08:04:24.631850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110d5adc1a02'
down_revision = '314c38d19e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('courier', 'hash_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('hash_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('courier', 'password')
    # ### end Alembic commands ###
