"""New Migration

Revision ID: 314c38d19e23
Revises: 97f65cb57b68
Create Date: 2021-09-29 07:36:37.122469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314c38d19e23'
down_revision = '97f65cb57b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
