"""New Migration

Revision ID: 337008a9305f
Revises: 7b045b54c576
Create Date: 2021-09-29 11:41:51.678347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337008a9305f'
down_revision = '7b045b54c576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name_user', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('famaly_name_user', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('phone_user', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('email_user', sa.String(length=1000), nullable=True))
    op.add_column('orders', sa.Column('adress_user', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'adress_user')
    op.drop_column('orders', 'email_user')
    op.drop_column('orders', 'phone_user')
    op.drop_column('orders', 'famaly_name_user')
    op.drop_column('orders', 'name_user')
    # ### end Alembic commands ###
