"""New Migration

Revision ID: 3c0978a2ab93
Revises: 860d3d45e04a
Create Date: 2021-10-07 10:14:19.297194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0978a2ab93'
down_revision = '860d3d45e04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
