"""New Migration

Revision ID: 6e712eebea0f
Revises: 110d5adc1a02
Create Date: 2021-09-29 08:05:20.351553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e712eebea0f'
down_revision = '110d5adc1a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('courier', 'hash_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('hash_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('courier', 'password')
    # ### end Alembic commands ###
