"""New Migration

Revision ID: 7b045b54c576
Revises: 6e712eebea0f
Create Date: 2021-09-29 08:13:58.224209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b045b54c576'
down_revision = '6e712eebea0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
