"""New Migration

Revision ID: 8e593c5d856a
Revises: ab6262e18d2b
Create Date: 2021-11-04 10:21:59.610721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e593c5d856a'
down_revision = 'ab6262e18d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('norm_password', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier', 'norm_password')
    # ### end Alembic commands ###
