"""New Migration

Revision ID: 8f006c74a13c
Revises: 337008a9305f
Create Date: 2021-09-29 16:27:35.507468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f006c74a13c'
down_revision = '337008a9305f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
