"""New Migration22

Revision ID: 97f65cb57b68
Revises: f50314ff1f33
Create Date: 2021-09-28 19:50:52.553527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f65cb57b68'
down_revision = 'f50314ff1f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('photo_dostavka', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'photo_dostavka')
    # ### end Alembic commands ###
