"""New Migration

Revision ID: a61bd2b1a09c
Revises: db6f0988295e
Create Date: 2021-10-18 10:52:12.938540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61bd2b1a09c'
down_revision = 'db6f0988295e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
