"""New Migration

Revision ID: ab6262e18d2b
Revises: a61bd2b1a09c
Create Date: 2021-10-25 11:21:57.211156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6262e18d2b'
down_revision = 'a61bd2b1a09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
