"""New Migration

Revision ID: db6f0988295e
Revises: 3c0978a2ab93
Create Date: 2021-10-15 12:04:26.861089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6f0988295e'
down_revision = '3c0978a2ab93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
