"""New Migration

Revision ID: f50314ff1f33
Revises: 
Create Date: 2021-09-28 19:45:51.402429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50314ff1f33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('photo_dostavka', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'photo_dostavka')
    # ### end Alembic commands ###
