"""New Migration

Revision ID: 0939741fd567
Revises: 2d4d2d1e285c
Create Date: 2021-10-07 10:13:33.336569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0939741fd567'
down_revision = '2d4d2d1e285c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
