"""New Migration

Revision ID: 10915da6099a
Revises: cdee4b3a5888
Create Date: 2021-10-11 16:18:29.851041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10915da6099a'
down_revision = 'cdee4b3a5888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_basket', sa.Column('succes_oplata', sa.Boolean(), nullable=True))
    op.add_column('history_basket', sa.Column('succes_dostavka_curer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_basket', 'succes_dostavka_curer')
    op.drop_column('history_basket', 'succes_oplata')
    # ### end Alembic commands ###
