"""New Migration

Revision ID: 11c06c0139ad
Revises: 4ea4db37a5a7
Create Date: 2021-11-04 10:28:06.100399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c06c0139ad'
down_revision = '4ea4db37a5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('normpassword', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'normpassword')
    # ### end Alembic commands ###
