"""New Migration

Revision ID: 2d4d2d1e285c
Revises: 
Create Date: 2021-10-06 10:02:33.797771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4d2d1e285c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=1000), nullable=False))
    op.add_column('history_basket', sa.Column('spisbonuys', sa.BigInteger(), nullable=True))
    op.add_column('reason', sa.Column('icon', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reason', 'icon')
    op.drop_column('history_basket', 'spisbonuys')
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
