"""New Migration

Revision ID: 3b8a6585b4c7
Revises: 814898f2e2e7
Create Date: 2021-10-15 12:03:24.411573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8a6585b4c7'
down_revision = '814898f2e2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
