"""New Migration

Revision ID: 48d69d1983fa
Revises: cc7dff4ae674
Create Date: 2021-09-30 07:40:58.817568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d69d1983fa'
down_revision = 'cc7dff4ae674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_basket', sa.Column('admin_bool_dostavka', sa.Boolean(), nullable=True))
    op.add_column('history_basket', sa.Column('admin_send_curer', sa.Boolean(), nullable=True))
    op.add_column('history_basket', sa.Column('photo_otchet', sa.String(length=1000), nullable=True))
    op.add_column('history_basket', sa.Column('send_id_curer', sa.Integer(), nullable=True))
    op.add_column('history_basket', sa.Column('send_name_curer', sa.Integer(), nullable=True))
    op.drop_column('history_basket', 'dostavka')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_basket', sa.Column('dostavka', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('history_basket', 'send_name_curer')
    op.drop_column('history_basket', 'send_id_curer')
    op.drop_column('history_basket', 'photo_otchet')
    op.drop_column('history_basket', 'admin_send_curer')
    op.drop_column('history_basket', 'admin_bool_dostavka')
    # ### end Alembic commands ###
