"""New Migration

Revision ID: 4ea4db37a5a7
Revises: d3e70f25e5dd
Create Date: 2021-11-04 10:27:16.170478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea4db37a5a7'
down_revision = 'd3e70f25e5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('normpassword', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'normpassword')
    # ### end Alembic commands ###
