"""New Migration2

Revision ID: 5eb3c8549a8e
Revises: af3718e36e9d
Create Date: 2021-09-27 20:42:23.065759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb3c8549a8e'
down_revision = 'af3718e36e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points22', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points22')
    # ### end Alembic commands ###
