"""New Migration

Revision ID: 5fa77d5f8f30
Revises: 3b8a6585b4c7
Create Date: 2021-10-15 12:57:08.871359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa77d5f8f30'
down_revision = '3b8a6585b4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
