"""New Migration

Revision ID: 7a9a69a37604
Revises: 5fa77d5f8f30
Create Date: 2021-10-15 13:00:00.113958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9a69a37604'
down_revision = '5fa77d5f8f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
