"""New Migration

Revision ID: 803b53507f8e
Revises: 0939741fd567
Create Date: 2021-10-10 16:27:14.617468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803b53507f8e'
down_revision = '0939741fd567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###
