"""New Migration

Revision ID: 814898f2e2e7
Revises: 10915da6099a
Create Date: 2021-10-12 11:27:22.135822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814898f2e2e7'
down_revision = '10915da6099a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('serial_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'serial_number')
    # ### end Alembic commands ###
