"""New Migration

Revision ID: 928a4ed510a4
Revises: e638e0c0924a
Create Date: 2021-10-25 13:15:12.708301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928a4ed510a4'
down_revision = 'e638e0c0924a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('present', sa.Column('sort_id_catalog', sa.Integer(), nullable=True))
    op.add_column('present', sa.Column('sort_id_popularnoe', sa.Integer(), nullable=True))
    op.add_column('present', sa.Column('sort_id_novinki', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('present', 'sort_id_novinki')
    op.drop_column('present', 'sort_id_popularnoe')
    op.drop_column('present', 'sort_id_catalog')
    # ### end Alembic commands ###
