"""New Migration

Revision ID: b7a9c1ca84bf
Revises: 2fa0be7db145
Create Date: 2021-10-29 06:27:03.716016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a9c1ca84bf'
down_revision = '2fa0be7db145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
