"""New Migration3

Revision ID: cc7dff4ae674
Revises: 5eb3c8549a8e
Create Date: 2021-09-27 20:47:55.880848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7dff4ae674'
down_revision = '5eb3c8549a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points22')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points22', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
