"""New Migration

Revision ID: cdee4b3a5888
Revises: 803b53507f8e
Create Date: 2021-10-10 16:27:44.695952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdee4b3a5888'
down_revision = '803b53507f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###
