"""New Migration

Revision ID: cfc64f3fb424
Revises: 928a4ed510a4
Create Date: 2021-10-25 13:36:57.763236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc64f3fb424'
down_revision = '928a4ed510a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
