"""New Migration

Revision ID: d3e70f25e5dd
Revises: 183ac7da32b8
Create Date: 2021-11-04 09:09:12.909888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e70f25e5dd'
down_revision = '183ac7da32b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('sort_present_read', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('sort_category_read', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('akcia_read', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('sort_present_change', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('sort_category_change', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('akcia_change', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('admins_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('courer_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('history_basket_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('present_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('filters_present_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('users_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('comments_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('podpiska_delete', sa.Boolean(), nullable=True))
    op.add_column('admin', sa.Column('akcia_delete', sa.Boolean(), nullable=True))
    op.create_index('ix_present_popular_id', 'present', ['popular', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_present_popular_id', table_name='present')
    op.drop_column('admin', 'akcia_delete')
    op.drop_column('admin', 'podpiska_delete')
    op.drop_column('admin', 'comments_delete')
    op.drop_column('admin', 'users_delete')
    op.drop_column('admin', 'filters_present_delete')
    op.drop_column('admin', 'present_delete')
    op.drop_column('admin', 'history_basket_delete')
    op.drop_column('admin', 'courer_delete')
    op.drop_column('admin', 'admins_delete')
    op.drop_column('admin', 'akcia_change')
    op.drop_column('admin', 'sort_category_change')
    op.drop_column('admin', 'sort_present_change')
    op.drop_column('admin', 'akcia_read')
    op.drop_column('admin', 'sort_category_read')
    op.drop_column('admin', 'sort_present_read')
    # ### end Alembic commands ###
