"""New Migration

Revision ID: e638e0c0924a
Revises: a4847faf169d
Create Date: 2021-10-25 11:20:51.111588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e638e0c0924a'
down_revision = 'a4847faf169d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('present', sa.Column('popular', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('present', 'popular')
    # ### end Alembic commands ###
